# Generated by Django 5.0.3 on 2024-03-19 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name': 'Manufacture',
                'verbose_name_plural': 'Manufactures',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('car_year', models.IntegerField(max_length=4)),
                ('car_description', models.TextField()),
                ('car_number', models.CharField(max_length=8, unique=True)),
                ('car_color', models.CharField(max_length=50)),
                ('car_price', models.DecimalField(decimal_places=3, max_digits=255)),
                ('made_in', models.CharField(max_length=30)),
                ('car_image', models.FileField(upload_to='cars_images')),
                ('car_created_at', models.DateTimeField(auto_now_add=True)),
                ('car_manufacturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.manufacturer')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars ',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
                ('user_name', models.CharField(max_length=70, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=30, unique=True)),
                ('user_image', models.FileField(upload_to='users_images')),
                ('liked_cars', models.ManyToManyField(to='cars.cars')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AddField(
            model_name='cars',
            name='car_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.users'),
        ),
    ]
